__title__ = 'vnav'
__description__ = 'vNAV processing'
__url__ = 'https://github.com/harvard-nrg/vnav'
__version__ = '0.1.0'
__author__ = 'Neuroinformatics Research Group'
__author_email__ = 'info@neuroinfo.org'
